# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - jadestestedutaskhub(Production), Build and deploy container app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io/
        username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_AE8F38AB0F50411BB9A793F87008F276 }}
        password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_334D04CCE6004C7EA859E40C8984A9BF }}

    - run: |
        docker build . -t ghcr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_AE8F38AB0F50411BB9A793F87008F276 }}/edutaskhub:${{ github.sha }}
        docker push ghcr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_AE8F38AB0F50411BB9A793F87008F276 }}/edutaskhub:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: jadestestedutaskhub
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_51605F672F2742CA84B1F75B180803CC }}
        images: ghcr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_AE8F38AB0F50411BB9A793F87008F276 }}/edutaskhub:${{ github.sha }}

